apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: devops
spec:
  selector:
    app: gitea
  ports:
    - name: gitea-http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: gitea-https
      protocol: TCP
      port: 443
      targetPort: 3001
