apiVersion: v1
kind: Service
metadata:
  name: gitea-nginx-service
  namespace: devops
spec:
  selector:
    app: gitea-nginx
  ports:
    - name: gitea-nginx-http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: gitea-nginx-https
      protocol: TCP
      port: 443
      targetPort: 443
