apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-volume
  namespace: devops
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/sorriso/Documents/GitHub/kube-gitea-dockerhub/volume/"
  capacity:
    storage: 1Gi
  claimRef:
    name: gitea-volume-claim
    namespace: devops
